/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/datacenter/': RouteRecordInfo<'/datacenter/', '/datacenter', Record<never, never>, Record<never, never>>,
    '/edit/': RouteRecordInfo<'/edit/', '/edit', Record<never, never>, Record<never, never>>,
    '/error/403/': RouteRecordInfo<'/error/403/', '/error/403', Record<never, never>, Record<never, never>>,
    '/error/404/': RouteRecordInfo<'/error/404/', '/error/404', Record<never, never>, Record<never, never>>,
    '/error/500/': RouteRecordInfo<'/error/500/', '/error/500', Record<never, never>, Record<never, never>>,
    '/error/ErrorPage': RouteRecordInfo<'/error/ErrorPage', '/error/ErrorPage', Record<never, never>, Record<never, never>>,
    '/home/': RouteRecordInfo<'/home/', '/home', Record<never, never>, Record<never, never>>,
    '/login/PasswordLoginPage': RouteRecordInfo<'/login/PasswordLoginPage', '/login/PasswordLoginPage', Record<never, never>, Record<never, never>>,
    '/login/PhoneLoginPage': RouteRecordInfo<'/login/PhoneLoginPage', '/login/PhoneLoginPage', Record<never, never>, Record<never, never>>,
    '/login/VerifyCodePage': RouteRecordInfo<'/login/VerifyCodePage', '/login/VerifyCodePage', Record<never, never>, Record<never, never>>,
    '/my/': RouteRecordInfo<'/my/', '/my', Record<never, never>, Record<never, never>>,
    '/notice/': RouteRecordInfo<'/notice/', '/notice', Record<never, never>, Record<never, never>>,
    '/publish/': RouteRecordInfo<'/publish/', '/publish', Record<never, never>, Record<never, never>>,
    '/search/': RouteRecordInfo<'/search/', '/search', Record<never, never>, Record<never, never>>,
    '/setting/': RouteRecordInfo<'/setting/', '/setting', Record<never, never>, Record<never, never>>,
    '/talklist/': RouteRecordInfo<'/talklist/', '/talklist', Record<never, never>, Record<never, never>>,
  }
}
